import type { SubscriptionPlan } from "@/lib/billing/types"

const now = new Date().toISOString()

export const fallbackPlans: SubscriptionPlan[] = [
  {
    id: "fallback_starter",
    name: "STARTER",
    display_name: "Starter",
    description: "Para agencias chicas que quieren ordenar su operación.",
    price_monthly: 79990,
    price_yearly: null,
    mp_preapproval_amount: 79990,
    currency: "ARS",
    max_users: null,
    max_operations_per_month: null,
    max_integrations: null,
    max_storage_mb: 4096,
    max_api_calls_per_day: 15000,
    features: {
      cerebro: false,
      emilia: false,
      whatsapp: true,
      reports: true,
      crm: true,
      marketing_ads: false,
      custom_integrations: false,
      priority_support: false,
    },
    is_active: true,
    is_public: true,
    sort_order: 1,
    created_at: now,
    updated_at: now,
  },
  {
    id: "fallback_pro",
    name: "PRO",
    display_name: "Pro",
    description: "El plan mas elegido para equipos en crecimiento.",
    price_monthly: 99990,
    price_yearly: null,
    mp_preapproval_amount: 99990,
    currency: "ARS",
    max_users: null,
    max_operations_per_month: null,
    max_integrations: null,
    max_storage_mb: 10240,
    max_api_calls_per_day: 60000,
    features: {
      cerebro: true,
      emilia: true,
      whatsapp: true,
      reports: true,
      crm: true,
      marketing_ads: false,
      custom_integrations: false,
      priority_support: false,
    },
    is_active: true,
    is_public: true,
    sort_order: 2,
    created_at: now,
    updated_at: now,
  },
  {
    id: "fallback_enterprise",
    name: "ENTERPRISE",
    display_name: "Enterprise",
    description: "Contactanos para una solucion a medida.",
    price_monthly: 0,
    price_yearly: null,
    mp_preapproval_amount: null,
    currency: "ARS",
    max_users: null,
    max_operations_per_month: null,
    max_integrations: null,
    max_storage_mb: null,
    max_api_calls_per_day: null,
    features: {
      cerebro: true,
      emilia: true,
      whatsapp: true,
      reports: true,
      crm: true,
      marketing_ads: true,
      custom_integrations: true,
      priority_support: true,
    },
    is_active: true,
    is_public: true,
    sort_order: 3,
    created_at: now,
    updated_at: now,
  },
]

export const fallbackPlansMeta = {
  source: "fallback",
  reason: "missing_tables",
  generated_at: now,
}
