import type { SubscriptionPlan } from "@/lib/billing/types"

const now = new Date().toISOString()

export const fallbackPlans: SubscriptionPlan[] = [
  {
    id: "fallback_starter",
    name: "STARTER",
    display_name: "Starter",
    description: "Para agencias chicas que quieren ordenar su operación.",
    price_monthly: 25000,
    price_yearly: null,
    mp_preapproval_amount: 25000,
    currency: "ARS",
    max_users: 3,
    max_operations_per_month: 300,
    max_integrations: 2,
    max_storage_mb: 1024,
    max_api_calls_per_day: 3000,
    features: {
      cerebro: false,
      emilia: false,
      whatsapp: true,
      reports: false,
      crm: true,
      marketing_ads: false,
      custom_integrations: false,
      priority_support: false,
    },
    is_active: true,
    is_public: true,
    sort_order: 1,
    created_at: now,
    updated_at: now,
  },
  {
    id: "fallback_pro",
    name: "PRO",
    display_name: "Pro",
    description: "El plan mas elegido para equipos en crecimiento.",
    price_monthly: 45000,
    price_yearly: null,
    mp_preapproval_amount: 45000,
    currency: "ARS",
    max_users: 10,
    max_operations_per_month: 1500,
    max_integrations: 6,
    max_storage_mb: 4096,
    max_api_calls_per_day: 15000,
    features: {
      cerebro: true,
      emilia: true,
      whatsapp: true,
      reports: true,
      crm: true,
      marketing_ads: true,
      custom_integrations: false,
      priority_support: false,
    },
    is_active: true,
    is_public: true,
    sort_order: 2,
    created_at: now,
    updated_at: now,
  },
  {
    id: "fallback_business",
    name: "BUSINESS",
    display_name: "Business",
    description: "Para agencias con alto volumen y necesidades avanzadas.",
    price_monthly: 90000,
    price_yearly: null,
    mp_preapproval_amount: 90000,
    currency: "ARS",
    max_users: 30,
    max_operations_per_month: 6000,
    max_integrations: 15,
    max_storage_mb: 10240,
    max_api_calls_per_day: 60000,
    features: {
      cerebro: true,
      emilia: true,
      whatsapp: true,
      reports: true,
      crm: true,
      marketing_ads: true,
      custom_integrations: true,
      priority_support: true,
    },
    is_active: true,
    is_public: true,
    sort_order: 3,
    created_at: now,
    updated_at: now,
  },
]

export const fallbackPlansMeta = {
  source: "fallback",
  reason: "missing_tables",
  generated_at: now,
}
